"""字幕网页操作台 HTML 页面。"""
from __future__ import annotations

from html import escape
from typing import Any

from starlette.responses import HTMLResponse


def render_console(owner: Any) -> HTMLResponse:
    """渲染移动端字幕操作台页面。"""
    title = escape(str(getattr(owner, "_console_title", "字幕操作台") or "字幕操作台"))
    html = f'''<!doctype html>
<html lang="zh-CN"><head><meta charset="utf-8" />
<meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1,viewport-fit=cover" />
<title>{title}</title>
<style>
:root {{ color-scheme: light dark; --bg:#f5f7ff; --ink:#121827; --muted:#667085; --card:rgba(255,255,255,.78); --soft:rgba(255,255,255,.54); --line:rgba(65,75,110,.14); --a:#705cff; --b:#00d4ff; --ok:#15a36b; --bad:#e5484d; --warn:#f59e0b; --shadow:0 22px 80px rgba(34,42,80,.16); }}
html[data-theme="dark"] {{ color-scheme: dark; --bg:#080b12; --ink:#eef4ff; --muted:#98a2b3; --card:rgba(18,24,38,.78); --soft:rgba(28,35,52,.62); --line:rgba(210,225,255,.12); --a:#8ea2ff; --b:#00e5ff; --ok:#62d394; --bad:#ff7b7b; --warn:#ffd166; --shadow:0 24px 90px rgba(0,0,0,.42); }}
@media (prefers-color-scheme: dark) {{ html:not([data-theme="light"]) {{ color-scheme: dark; --bg:#080b12; --ink:#eef4ff; --muted:#98a2b3; --card:rgba(18,24,38,.78); --soft:rgba(28,35,52,.62); --line:rgba(210,225,255,.12); --a:#8ea2ff; --b:#00e5ff; --ok:#62d394; --bad:#ff7b7b; --warn:#ffd166; --shadow:0 24px 90px rgba(0,0,0,.42); }} }}
* {{ box-sizing:border-box; -webkit-tap-highlight-color:transparent; }} body {{ margin:0; min-height:100vh; color:var(--ink); font-family:-apple-system,BlinkMacSystemFont,'SF Pro Display','Segoe UI',sans-serif; background:radial-gradient(circle at 10% -10%, rgba(112,92,255,.36), transparent 28%), radial-gradient(circle at 92% 4%, rgba(0,212,255,.28), transparent 30%), radial-gradient(circle at 50% 110%, rgba(21,163,107,.18), transparent 35%), var(--bg); }}
.wrap {{ max-width:980px; margin:0 auto; padding:14px 14px 32px; }} .glass {{ background:var(--card); border:1px solid var(--line); box-shadow:var(--shadow); backdrop-filter:blur(20px); border-radius:28px; position:relative; overflow:hidden; }} .glass:before {{ content:''; position:absolute; inset:0; background:linear-gradient(135deg,rgba(255,255,255,.20),transparent 42%,rgba(0,212,255,.09)); pointer-events:none; }}
.hero {{ padding:18px; min-height:174px; display:flex; flex-direction:column; justify-content:space-between; }} .top {{ display:flex; justify-content:space-between; gap:12px; align-items:flex-start; position:relative; z-index:1; }} .brand {{ display:flex; gap:12px; align-items:center; }} .logo {{ width:54px; height:54px; border-radius:20px; display:grid; place-items:center; background:linear-gradient(135deg,var(--a),var(--b)); color:white; font-size:28px; box-shadow:0 16px 36px rgba(0,212,255,.25); }} h1 {{ margin:0; font-size:28px; letter-spacing:-.05em; }} h2 {{ margin:0 0 12px; font-size:18px; letter-spacing:-.03em; }} p,.muted {{ color:var(--muted); line-height:1.55; }} .status {{ font-size:13px; color:var(--muted); }}
.flow {{ display:grid; grid-template-columns:repeat(4,1fr); gap:9px; margin-top:16px; position:relative; z-index:1; }} .flow div {{ padding:10px 8px; border:1px solid var(--line); background:var(--soft); border-radius:18px; text-align:center; }} .flow b {{ display:block; font-size:20px; }} .flow span {{ color:var(--muted); font-size:12px; }}
.nav {{ position:sticky; top:0; z-index:20; display:flex; gap:8px; overflow:auto; padding:10px 0; backdrop-filter:blur(16px); }} .nav button {{ flex:0 0 auto; }}
.card {{ margin-top:14px; padding:16px; }} .grid {{ display:grid; grid-template-columns:repeat(auto-fit,minmax(150px,1fr)); gap:10px; }} .row {{ display:flex; gap:9px; flex-wrap:wrap; align-items:center; }} input,select,button {{ font:inherit; border-radius:16px; border:1px solid var(--line); padding:11px 13px; outline:none; }} input,select {{ width:100%; background:var(--soft); color:var(--ink); }} button {{ border:0; color:white; font-weight:760; background:linear-gradient(135deg,var(--a),var(--b)); box-shadow:0 10px 24px rgba(0,160,255,.20); }} button.secondary {{ background:var(--soft); color:var(--a); border:1px solid rgba(0,212,255,.30); box-shadow:none; }} button.danger {{ background:linear-gradient(135deg,var(--bad),#ff9966); }} button.ok {{ background:linear-gradient(135deg,var(--ok),#20d6a5); }} button.mini {{ padding:5px 9px; font-size:12px; border-radius:10px; box-shadow:none; }} button:active {{ transform:scale(.985); }}
.drop {{ display:block; border:1.8px dashed rgba(0,212,255,.42); background:rgba(0,212,255,.10); border-radius:24px; padding:24px 14px; text-align:center; transition:.18s; }} .drop.drag {{ transform:scale(1.01); background:rgba(112,92,255,.16); }} .drop input {{ display:none; }} .drop-icon {{ font-size:36px; }} .drop-title {{ font-size:17px; font-weight:850; margin:8px 0 5px; }}
.media-grid {{ display:grid; grid-template-columns:repeat(auto-fill,minmax(300px,1fr)); gap:14px; margin-top:12px; }} .media-card {{ display:grid; grid-template-columns:72px 1fr auto; gap:12px; align-items:stretch; border-top:1px solid var(--line); padding:12px 0; text-align:left; }} .poster {{ width:72px; min-height:104px; border-radius:16px; overflow:hidden; background:linear-gradient(145deg,var(--a),var(--b)); display:grid; place-items:center; color:white; font-weight:900; box-shadow:0 12px 28px rgba(0,0,0,.18); }} .poster img {{ width:100%; height:100%; object-fit:cover; display:block; }} .media-main {{ min-width:0; }} .media-title {{ font-size:17px; font-weight:900; margin-bottom:5px; }} .media-meta {{ color:var(--muted); font-size:12px; line-height:1.45; }} .media-actions {{ margin-top:9px; display:flex; gap:8px; flex-wrap:wrap; }} .detail-panel {{ margin-top:14px; }} .detail-head {{ display:grid; grid-template-columns:auto auto 1fr; gap:12px; align-items:center; padding:12px 0; border-top:1px solid var(--line); }} .season-strip {{ display:flex; gap:8px; overflow:auto; padding:8px 0; }} .season-strip button.active {{ background:linear-gradient(135deg,var(--a),var(--b)); color:white; }} .episode-list {{ display:grid; gap:8px; }} .target-card {{ border:1px solid var(--line); border-radius:18px; padding:11px; display:grid; grid-template-columns:auto 58px 1fr auto; gap:10px; align-items:start; background:var(--soft); }} .target-card b {{ display:block; }} .poster-mini {{ width:58px; height:84px; border-radius:14px; overflow:hidden; background:linear-gradient(145deg,var(--a),var(--b)); display:grid; place-items:center; color:white; font-weight:900; }} .poster-mini img {{ width:100%; height:100%; object-fit:cover; }} .item {{ border-top:1px solid var(--line); padding:12px 0; }} .pill {{ display:inline-flex; padding:4px 9px; border-radius:999px; border:1px solid var(--line); background:var(--soft); color:var(--muted); font-size:12px; margin:2px; }} .file-row {{ display:flex; justify-content:space-between; gap:10px; padding:9px 0; border-top:1px solid var(--line); text-align:left; }} pre {{ white-space:pre-wrap; word-break:break-all; max-height:290px; overflow:auto; padding:12px; border-radius:18px; border:1px solid var(--line); background:var(--soft); color:var(--muted); }}
.progress {{ margin-top:10px; padding:12px; border-radius:16px; background:rgba(79,107,255,.10); border:1px solid rgba(79,107,255,.20); }} .progress-head {{ display:flex; justify-content:space-between; gap:10px; font-size:13px; margin-bottom:8px; }} .progress-track {{ height:10px; border-radius:999px; overflow:hidden; background:rgba(148,163,184,.25); }} .progress-track i {{ display:block; width:0%; height:100%; border-radius:999px; background:linear-gradient(90deg,var(--a),var(--b)); transition:width .18s ease; }}
.toast-wrap {{ position:fixed; left:14px; right:14px; bottom:calc(14px + env(safe-area-inset-bottom)); z-index:99; display:flex; flex-direction:column; gap:8px; pointer-events:none; }} .toast {{ pointer-events:auto; border-radius:17px; padding:12px 14px; color:white; box-shadow:0 18px 44px rgba(0,0,0,.28); animation:pop .2s ease; }} .toast.ok {{ background:#129568; }} .toast.err {{ background:#d64545; }} .toast.info {{ background:#3867d6; }} @keyframes pop {{ from {{ transform:translateY(10px); opacity:0; }} to {{ transform:translateY(0); opacity:1; }} }}
@media (max-width:560px) {{ .flow {{ grid-template-columns:repeat(2,1fr); }} h1 {{ font-size:24px; }} .hero {{ min-height:190px; }} }}
</style></head>
<body><div class="wrap">
<section class="glass hero"><div class="top"><div class="brand"><div class="logo">⌁</div><div><h1>{title}</h1><div id="status" class="status">正在连接...</div></div></div><div id="heroPoster"></div><button class="secondary" onclick="toggleTheme()" id="themeBtn">跟随系统</button></div><p>选片、拖字幕、点上传。需要在线字幕或 AI 翻译时，再打开对应工具。</p><div class="flow"><div><b>1</b><span>找影片</span></div><div><b>2</b><span>选集数</span></div><div><b>3</b><span>拖字幕</span></div><div><b>4</b><span>上传</span></div></div></section>
<div class="nav"><button class="secondary" onclick="jump('pick')">找影片</button><button class="secondary" onclick="jump('upload')">上传</button><button class="secondary" onclick="jump('online')">在线字幕</button><button class="secondary" onclick="jump('manage')">字幕管理</button><button class="secondary" onclick="jump('ai')">AI翻译</button></div>
<section id="pick" class="glass card"><h2>找影片</h2><p class="muted">从 MoviePilot 本地库选择资源，网页操作台会展示海报、季和目标集数。</p><div class="grid"><input id="kw" placeholder="搜电影 / 剧集 / 文件关键词"><select id="mt"><option value="all">全部</option><option value="movie">电影</option><option value="tv">剧集</option></select><button onclick="searchMedia()">搜索</button></div><div id="medias" class="media-grid"></div><div id="detail" class="detail-panel" style="display:none"><div class="detail-head"><button class="secondary" onclick="resetMedia()">返回搜索</button><div id="detailPoster"></div><div><h2 id="detailTitle">目标详情</h2><div id="detailStat" class="muted"></div></div></div><div id="seasonStrip" class="season-strip"></div><div class="row" style="margin:12px 0"><button class="secondary" onclick="toggleSelectAllTargets()">全选/取消</button><button class="secondary" onclick="invertTargets()">反选</button><input id="rangeInput" style="max-width:120px" placeholder="1-12"><button class="secondary" onclick="selectRange()">范围</button><button class="secondary" onclick="clearTargets()">清空</button><button onclick="saveSelection()">保存选择</button></div><div id="selected" class="muted" style="margin:8px 0"></div><div id="targets" class="episode-list">先选一部影片</div></div></section>
<section id="upload" class="glass card"><h2>上传字幕</h2><label id="drop" class="drop"><input id="files" type="file" multiple accept=".ass,.srt,.ssa,.vtt,.zip,.rar,.7z"><div class="drop-icon">☁️</div><div class="drop-title">把字幕拖到这里</div><div class="muted">支持 ass / srt / ssa / vtt / zip / rar / 7z</div><div id="fileList"></div></label><div class="row" style="margin-top:10px"><button onclick="prepareUpload()">刷新预览</button><button class="ok" onclick="applyUpload()">上传</button><button class="secondary" onclick="clearPickedFiles()">清空文件</button></div><div id="uploadProgress" class="progress" style="display:none"><div class="progress-head"><b id="progressLabel">准备上传</b><span id="progressMeta">0% · 等待开始</span></div><div class="progress-track"><i id="progressBar"></i></div></div><div id="preview"></div></section>
<section id="online" class="glass card"><h2>在线字幕</h2><p class="muted">直接从字幕源搜索，选中结果后可生成上传预览。</p><div class="row"><button onclick="onlineSearch()">搜索在线字幕</button><button class="ok" onclick="onlinePreview()">预览选中结果</button></div><div id="onlineList"></div></section>
<section id="manage" class="glass card"><h2>字幕管理</h2><p class="muted">查看、删除或重新处理已上传的外挂字幕。</p><div class="row"><button class="secondary" onclick="refreshSubtitles()">刷新列表</button><button class="danger" onclick="deleteSelectedSubtitles()">删除选中</button><button class="ok" onclick="fixSelectedSubtitles()">重新处理时间轴</button></div><div id="subtitleList"></div></section>
<section id="ai" class="glass card"><h2>AI翻译</h2><p class="muted">提交、查看或取消 AI 翻译/生成任务。取消任务不会删除已上传字幕。</p><div class="row"><button class="secondary" onclick="aiPreview()">检查</button><button class="ok" onclick="aiSubmit()">提交 AI</button><button class="secondary" onclick="tasks()">状态</button><button class="danger" onclick="aiCancel()">取消任务</button></div></section>
<section class="glass card"><h2>日志</h2><pre id="out">准备好了</pre></section>
</div><div class="toast-wrap" id="toasts"></div>
<script>
const P='/api/v1/plugin/SubtitleWebUploader'; let currentTargets=[]; let selectedTargets=[]; let lastPreview=null; let currentMedia=null; let currentSeasons=[]; let selectedSeason='all'; let allTargetCount=0; let pickedFiles=[]; let onlineResults=[];
function jump(id){{document.getElementById(id).scrollIntoView({{behavior:'smooth',block:'start'}})}}
function out(x){{document.getElementById('out').textContent=typeof x==='string'?x:JSON.stringify(x,null,2)}}
function toast(msg,type='info'){{const w=document.getElementById('toasts'); const d=document.createElement('div'); d.className='toast '+type; d.textContent=msg; w.appendChild(d); setTimeout(()=>{{d.style.opacity='0'; d.style.transform='translateY(8px)';}},2700); setTimeout(()=>d.remove(),3300)}}
async function jget(url){{let r=await fetch(url); let t=await r.text(); let data; try{{data=JSON.parse(t)}}catch(e){{throw new Error(t)}} if(!r.ok) throw new Error(data.detail||data.msg||r.statusText); return data}}
async function jpost(url,body){{let r=await fetch(url,{{method:'POST',headers:{{'Content-Type':'application/json'}},body:JSON.stringify(body||{{}})}}); let t=await r.text(); let data; try{{data=JSON.parse(t)}}catch(e){{throw new Error(t)}} if(!r.ok) throw new Error(data.detail||data.msg||r.statusText); return data}}
function setTheme(mode){{localStorage.setItem('subweb-theme',mode); applyTheme()}} function applyTheme(){{const m=localStorage.getItem('subweb-theme')||'system'; document.documentElement.dataset.theme=m==='system'?'':m; document.getElementById('themeBtn').textContent=m==='system'?'跟随系统':m==='dark'?'深色':'浅色'}} function toggleTheme(){{const m=localStorage.getItem('subweb-theme')||'system'; setTheme(m==='system'?'dark':m==='dark'?'light':'system'); toast('主题已切换','ok')}}
function posterUrl(m){{return m.poster_thumb_url||m.poster_url||m.image||m.cover||m.poster||''}}
function posterHtml(m,cls='poster'){{const u=posterUrl(m); const title=(m.title||m.name||'?').slice(0,1); return `<div class="${{cls}}">${{u?`<img src="${{u}}" onerror="this.parentNode.textContent='${{title}}'">`:title}}</div>`}}
function mediaTypeLabel(m){{return m.media_type||m.type||'媒体'}}
function mediaLabel(m){{return (m.title||m.name||'未命名')+(m.year?` (${{m.year}})`: '')}}
function targetLabel(t){{return t.label||t.target_label||t.episode_text||t.name||t.title||t.filename||t.id}}
function episodeIndex(t){{return (t.media_type==='tv'||currentMedia?.media_type==='tv')?`E${{String(t.episode||0).padStart(2,'0')}}`:'MOV'}}
function renderFiles(){{document.getElementById('fileList').innerHTML=pickedFiles.map((f,i)=>`<div class=file-row><span>${{f.name}}<br><span class=muted>${{(f.size/1024/1024).toFixed(2)}} MB</span></span><button class='mini danger' type='button' onclick='removePickedFile(${{i}})'>移除</button></div>`).join('')}}
function bindDrop(){{const drop=document.getElementById('drop'), input=document.getElementById('files'); document.getElementById('kw').addEventListener('keydown',e=>{{if(e.key==='Enter') searchMedia()}});
input.addEventListener('change',()=>{{pickedFiles=[...input.files]; renderFiles(); toast('已选择 '+pickedFiles.length+' 个文件','ok'); autoPrepareUpload()}}); ['dragenter','dragover'].forEach(e=>drop.addEventListener(e,ev=>{{ev.preventDefault(); drop.classList.add('drag')}})); ['dragleave','drop'].forEach(e=>drop.addEventListener(e,ev=>{{ev.preventDefault(); drop.classList.remove('drag')}})); drop.addEventListener('drop',ev=>{{pickedFiles=[...ev.dataTransfer.files]; renderFiles(); toast('已拖入 '+pickedFiles.length+' 个文件','ok'); autoPrepareUpload()}})}}
function removePickedFile(i){{pickedFiles.splice(i,1); lastPreview=null; renderFiles(); document.getElementById('preview').innerHTML=''; toast('已移除','ok')}} function clearPickedFiles(){{pickedFiles=[]; lastPreview=null; renderFiles(); document.getElementById('preview').innerHTML=''; const input=document.getElementById('files'); if(input) input.value=''; toast('已清空','ok')}} async function autoPrepareUpload(){{if(!selectedTargets.length){{toast('先选集数，再拖字幕','info'); return}} if(pickedFiles.length) await prepareUpload()}}
async function boot(){{applyTheme(); bindDrop(); try{{let s=await jget(P+'/subtitleweb_bridge/status'); document.getElementById('status').textContent='已连接：'+s.data.plugin_name+' '+s.data.plugin_version; out(s); toast('已就绪','ok')}}catch(e){{document.getElementById('status').textContent='连接失败'; toast(e.message,'err')}} loadSelection()}}
async function loadSelection(){{try{{let s=await jget(P+'/subtitleweb_bridge/selection?user_id=web'); selectedTargets=s.data.selected_target_ids||[]; renderSelected()}}catch(e){{}}}}
async function searchMedia(){{try{{let kw=encodeURIComponent(document.getElementById('kw').value); let mt=document.getElementById('mt').value; let r=await jget(P+`/subtitleweb_bridge/search?keyword=${{kw}}&media_type=${{mt}}&page_size=20`); out(r); let list=(r.data&&r.data.medias)||[]; document.getElementById('medias').innerHTML=list.map(m=>`<button class=media-card onclick='loadTargets(${{JSON.stringify(m)}})'>${{posterHtml(m)}}<div class=media-main><div class=media-meta>${{mediaTypeLabel(m)}}</div><div class=media-title>${{mediaLabel(m)}}</div><div class=media-meta>本地 ${{m.local_count||m.target_count||m.count||0}} 个目标 · TMDB ${{m.tmdb_id||m.tmdbid||'-'}}</div></div><span>›</span></button>`).join('')||'<p class=muted>无结果</p>'; document.getElementById('detail').style.display='none'; document.getElementById('medias').style.display='grid'; toast('找到 '+list.length+' 条','ok')}}catch(e){{toast(e.message,'err'); out(e.message)}}}}
async function loadTargets(m){{try{{currentMedia=m; let params=new URLSearchParams(); ['media_type','type','tmdb_id','tmdbid','douban_id','doubanid','title','name','year','season'].forEach(k=>{{if(m[k]) params.set(k.replace('tmdbid','tmdb_id').replace('doubanid','douban_id').replace('name','title'),m[k])}}); let r=await jget(P+'/subtitleweb_bridge/targets?'+params.toString()); out(r); const d=r.data||{{}}; currentTargets=(d.targets||d.items||d.files)||[]; currentSeasons=d.seasons||[]; selectedSeason=d.selected_season||m.season||selectedSeason||'all'; allTargetCount=d.all_target_count||currentTargets.length; document.getElementById('heroPoster').innerHTML=posterHtml(currentMedia,'poster-mini'); document.getElementById('detailPoster').innerHTML=posterHtml(currentMedia,'poster-mini'); document.getElementById('detailTitle').textContent=mediaLabel(currentMedia); renderSeasons(); renderTargets(); document.getElementById('detail').style.display='block'; document.getElementById('medias').style.display='none'; renderSelected(); toast('读取到 '+currentTargets.length+' 个目标','ok')}}catch(e){{toast(e.message,'err'); out(e.message)}}}}
function renderSeasons(){{const box=document.getElementById('seasonStrip'); if(!box) return; if(!currentSeasons.length){{box.innerHTML=''; return}} const total=allTargetCount||currentSeasons.reduce((n,s)=>n+(Number(s.local_count)||0),0); const items=[{{season:'all',name:'全部季',local_count:total}},...currentSeasons]; box.innerHTML=items.map(s=>`<button class="secondary ${{String(selectedSeason)===String(s.season)?'active':''}}" onclick="changeSeason('${{s.season}}')">${{s.name||('第 '+s.season+' 季')}} · ${{s.local_count||0}}</button>`).join('')}}
async function changeSeason(season){{selectedSeason=season; if(currentMedia) await loadTargets({{...currentMedia, season}})}}
function renderTargets(){{document.getElementById('targets').innerHTML=currentTargets.map(t=>`<label class=target-card><input type=checkbox value='${{t.id}}' onchange='toggleTarget(this)' ${{selectedTargets.includes(t.id)?'checked':''}}><div class=poster-mini>${{episodeIndex(t)}}</div><span><b>${{targetLabel(t)}}</b><span class=muted>${{t.relative_path||t.path||t.file_path||''}}</span><br><span class=pill>外挂 ${{t.subtitle_count || (t.subtitles||[]).length}}</span>${{t.is_stream?' <span class=pill>STRM</span>':''}}${{t.ai_task?' <span class=pill>AI任务</span>':''}}</span><button class='mini secondary' type='button' onclick='event.preventDefault(); selectedTargets=["${{t.id}}"] ; renderSelected(); jump("upload")'>单集上传</button></label>`).join('')||'<p class=muted>未找到本地目标</p>'; renderSelected()}}
function resetMedia(){{currentMedia=null; currentTargets=[]; currentSeasons=[]; selectedSeason='all'; allTargetCount=0; document.getElementById('detail').style.display='none'; document.getElementById('medias').style.display='grid'; document.getElementById('heroPoster').innerHTML=''}}
function toggleTarget(cb){{if(cb.checked&&!selectedTargets.includes(cb.value)) selectedTargets.push(cb.value); if(!cb.checked) selectedTargets=selectedTargets.filter(x=>x!==cb.value); renderSelected()}} function toggleSelectAllTargets(){{const ids=currentTargets.map(t=>t.id).filter(Boolean); const all=ids.length&&ids.every(id=>selectedTargets.includes(id)); selectedTargets=all?selectedTargets.filter(id=>!ids.includes(id)):[...new Set([...selectedTargets,...ids])]; renderTargets(); toast(all?'已取消当前列表':'已全选当前列表','ok')}} function invertTargets(){{const ids=currentTargets.map(t=>t.id).filter(Boolean); selectedTargets=[...new Set([...selectedTargets.filter(id=>!ids.includes(id)),...ids.filter(id=>!selectedTargets.includes(id))])]; renderTargets(); toast('已反选当前列表','ok')}} function selectRange(){{const raw=(document.getElementById('rangeInput').value||'').trim(); const m=raw.match(/^(\d+)\s*-\s*(\d+)$/); if(!m) return toast('范围格式如 1-12','err'); const a=Number(m[1]), b=Number(m[2]); const lo=Math.min(a,b), hi=Math.max(a,b); const ids=currentTargets.filter(t=>Number(t.episode)>=lo&&Number(t.episode)<=hi).map(t=>t.id); selectedTargets=[...new Set([...selectedTargets,...ids])]; renderTargets(); toast('已选择范围 '+lo+'-'+hi,'ok')}} function selectAllTargets(){{toggleSelectAllTargets()}} function clearTargets(){{selectedTargets=[]; if(currentMedia) loadTargets(currentMedia); renderSelected(); toast('已清空','ok')}} function renderSelected(){{const total=currentTargets.length||0; const txt=`已选 ${{selectedTargets.length}} / 当前 ${{total}} / 全部 ${{allTargetCount||total}} 个目标`; document.getElementById('selected').textContent=txt; const stat=document.getElementById('detailStat'); if(stat&&currentMedia) stat.textContent=txt}} async function saveSelection(){{try{{let r=await jpost(P+'/subtitleweb_bridge/selection/save',{{user_id:'web',target_ids:selectedTargets,media:currentMedia||{{}}}}); out(r); toast('已保存','ok')}}catch(e){{toast(e.message,'err')}}}}
function setUploadProgress(percent,label,loaded,total,start){{const wrap=document.getElementById('uploadProgress'),bar=document.getElementById('progressBar'),lab=document.getElementById('progressLabel'),meta=document.getElementById('progressMeta'); if(!wrap||!bar) return; wrap.style.display='block'; bar.style.width=Math.max(0,Math.min(100,percent))+'%'; if(lab) lab.textContent=label||'正在上传'; let eta='预计时间计算中'; if(start&&loaded&&total){{const sec=Math.max((Date.now()-start)/1000,.1), speed=loaded/sec, remain=Math.max((total-loaded)/Math.max(speed,1),0); eta=remain<1?'即将完成':'预计剩余 '+Math.ceil(remain)+' 秒'}} if(meta) meta.textContent=Math.round(percent)+'% · '+eta}}
function uploadPrepareRequest(fd,totalSize){{const start=Date.now(); setUploadProgress(0,'正在上传并生成预览',0,totalSize,start); toast('开始上传 '+pickedFiles.length+' 个文件','info'); return new Promise((resolve,reject)=>{{const xhr=new XMLHttpRequest(); xhr.open('POST',P+'/subtitleweb_bridge/upload/prepare'); xhr.upload.onprogress=e=>{{if(e.lengthComputable) setUploadProgress(Math.min(98,e.loaded/e.total*100),'正在上传并生成预览',e.loaded,e.total,start)}}; xhr.onload=()=>{{try{{const data=JSON.parse(xhr.responseText||'{{}}'); if(xhr.status>=200&&xhr.status<300){{setUploadProgress(100,'上传完成，预览已生成',totalSize,totalSize,start); resolve(data)}} else reject(new Error(data.detail||data.msg||xhr.statusText))}}catch(e){{reject(e)}}}}; xhr.onerror=()=>reject(new Error('上传失败，请检查网络')); xhr.send(fd)}})}}
async function prepareUpload(){{try{{toast('准备生成字幕匹配预览','info'); if(!selectedTargets.length) throw new Error('请先选集数'); if(!pickedFiles.length) throw new Error('请先拖入字幕'); let fd=new FormData(); fd.append('target_ids',JSON.stringify(selectedTargets)); let total=0; for(const f of pickedFiles){{fd.append('files',f); total+=f.size||0}} let data=await uploadPrepareRequest(fd,total); lastPreview=data; out(data); const items=(data.data&&data.data.items)||[]; document.getElementById('preview').innerHTML=items.map(i=>`<div class=item><b>${{i.source_name}}</b> → ${{i.output_name||'未匹配'}} <span class=pill>${{i.detected_label||''}}</span></div>`).join(''); toast('预览好了：'+items.length+' 条','ok'); return true}}catch(e){{lastPreview=null; toast(e.message,'err'); out(e.message); return false}}}}
function renderTimelineResult(data){{const written=((data||{{}}).data||{{}}).written||[]; if(!written.length) return; document.getElementById('preview').innerHTML='<div class=item><b>上传结果</b></div>'+written.map(w=>{{const t=w.timeline||{{}}; const status=t.enabled?(t.applied?'已处理':'无需调整'):'未处理'; return `<div class=item><b>${{w.output_name||w.source_name}}</b> <span class=pill>${{status}}</span><br><span class=muted>${{w.output_path||''}}</span></div>`}}).join('')}}
async function applyUpload(){{try{{if(!lastPreview||!lastPreview.data){{toast('正在准备上传','info'); const ok=await prepareUpload(); if(!ok) throw new Error('预览失败，不能上传')}} let r=await jpost(P+'/subtitleweb_bridge/upload/apply',{{confirm:true,fix_timeline:true,allow_risky_offset:false,session_id:lastPreview.data.session_id,items:lastPreview.data.items||[]}}); out(r); renderTimelineResult(r); const count=((r.data||{{}}).written||[]).length || (r.data||{{}}).count || 0; toast('上传完成：'+count+' 个','ok'); await refreshSubtitles().catch(()=>{{}})}}catch(e){{toast('上传失败：'+e.message,'err'); out(e.message)}}}}
async function refreshSubtitles(){{try{{if(!selectedTargets.length) throw new Error('请先选集数'); if(!currentMedia) throw new Error('请先选影片'); let params=new URLSearchParams(); ['media_type','type','tmdb_id','tmdbid','douban_id','doubanid','title','name','year','season'].forEach(k=>{{if(currentMedia[k]) params.set(k.replace('tmdbid','tmdb_id').replace('doubanid','douban_id').replace('name','title'),currentMedia[k])}}); let tr=await jget(P+'/subtitleweb_bridge/targets?'+params.toString()); currentTargets=(tr.data&&(tr.data.targets||tr.data.items||tr.data.files))||[]; const selectedSet=new Set(selectedTargets); const lines=[]; currentTargets.filter(t=>selectedSet.has(t.id)).forEach(t=>{{(t.subtitles||[]).forEach(sub=>{{lines.push({{target_id:t.id,target:t.episode_text||t.name||t.title||t.filename||t.id,name:sub.name||sub.filename||'',path:sub.path||sub.file_path||''}})}})}}); document.getElementById('subtitleList').innerHTML=lines.length?lines.map(s=>`<label class=item style='display:block'><input type=checkbox class='subtitle-check' data-target='${{s.target_id}}' data-path='${{s.path}}' data-name='${{s.name}}'> <b>${{s.name||'外挂字幕'}}</b><br><span class=muted>${{s.target}}<br>${{s.path}}</span></label>`).join(''):'<p class=muted>当前没有外挂字幕</p>'; toast('字幕列表：'+lines.length+' 条','ok')}}catch(e){{toast(e.message,'err'); out(e.message)}}}}
async function deleteSelectedSubtitles(){{try{{const checks=[...document.querySelectorAll('.subtitle-check:checked')]; if(!checks.length) throw new Error('请先勾选字幕'); const items=checks.map(c=>({{target_id:c.dataset.target,subtitle_path:c.dataset.path,subtitle_name:c.dataset.name}})); out(await jpost(P+'/subtitleweb_bridge/delete/preview',{{items}})); if(!confirm('删除选中的 '+items.length+' 个字幕？')) return; let r=await jpost(P+'/subtitleweb_bridge/delete/apply',{{confirm:true,items}}); out(r); toast(((r.data||{{}}).failed||[]).length?'删除完成，有失败项':'字幕已删除','ok'); await refreshSubtitles()}}catch(e){{toast(e.message,'err'); out(e.message)}}}}
async function fixSelectedSubtitles(){{try{{const checks=[...document.querySelectorAll('.subtitle-check:checked')]; if(!checks.length) throw new Error('请先勾选字幕'); const items=checks.map(c=>({{target_id:c.dataset.target,subtitle_path:c.dataset.path,subtitle_name:c.dataset.name}})); let r=await jpost(P+'/subtitleweb_bridge/timeline/fix',{{confirm:true,items,allow_risky_offset:false}}); out(r); toast(r.message||r.msg||'已提交处理','ok')}}catch(e){{toast(e.message,'err'); out(e.message)}}}}
async function onlineSearch(){{try{{if(!selectedTargets.length) throw new Error('请先选集数'); let r=await jpost(P+'/subtitleweb_bridge/online/search',{{target_ids:selectedTargets,scope:'auto'}}); out(r); onlineResults=((r.data||{{}}).results)||[]; document.getElementById('onlineList').innerHTML=onlineResults.length?onlineResults.map((x,i)=>`<label class=item style='display:block'><input type=checkbox class='online-check' value='${{i}}'> <b>${{x.name||x.title||x.filename||'在线字幕'}}</b><br><span class=muted>${{x.provider||''}} · ${{x.language||x.lang||''}}</span></label>`).join(''):'<p class=muted>没有搜到在线字幕</p>'; toast('在线结果：'+onlineResults.length+' 条','ok')}}catch(e){{toast(e.message,'err'); out(e.message)}}}}
async function onlinePreview(){{try{{const idx=[...document.querySelectorAll('.online-check:checked')].map(x=>Number(x.value)); if(!idx.length) throw new Error('请先勾选在线字幕'); let results=idx.map(i=>onlineResults[i]).filter(Boolean); let r=await jpost(P+'/subtitleweb_bridge/online/download_preview',{{target_ids:selectedTargets,results}}); lastPreview=r; out(r); document.getElementById('preview').innerHTML='<div class=item><b>在线字幕预览已生成</b></div>'; jump('upload'); toast('预览好了','ok')}}catch(e){{toast(e.message,'err'); out(e.message)}}}}
async function aiPreview(){{try{{let r=await jpost(P+'/subtitleweb_bridge/ai/preview',{{target_ids:selectedTargets}}); out(r); toast('检查完成','ok')}}catch(e){{toast(e.message,'err'); out(e.message)}}}} async function aiSubmit(){{try{{let r=await jpost(P+'/subtitleweb_bridge/ai/submit',{{confirm:true,target_ids:selectedTargets,source_policy:'auto',overwrite_policy:'skip'}}); out(r); toast(r.message||r.msg||'AI 已提交','ok')}}catch(e){{toast(e.message,'err'); out(e.message)}}}} async function aiCancel(){{try{{if(!selectedTargets.length) throw new Error('请先选集数'); if(!confirm('取消选中目标的 AI 任务？')) return; let r=await jpost(P+'/subtitleweb_bridge/ai/cancel',{{confirm:true,target_ids:selectedTargets}}); out(r); toast(r.message||r.msg||'AI 任务已取消','ok')}}catch(e){{toast(e.message,'err'); out(e.message)}}}} async function tasks(){{try{{let r=await jpost(P+'/subtitleweb_bridge/tasks',{{target_ids:selectedTargets,limit:100}}); out(r); toast('状态已刷新','ok')}}catch(e){{toast(e.message,'err'); out(e.message)}}}}
boot();
</script></body></html>'''
    return HTMLResponse(html)
